### ISSUE TITLE
Shows up in wrong position in Safari (desktop and mobile) and Chromium

### ISSUE THREAD

**Issue by acoreyj** [flouthoc/uglipop.js#1]
The modal shows up too far down and to the right on safari, both desktop and mobile.

![image](https://cloud.githubusercontent.com/assets/11298888/6670606/9d390f90-cbcd-11e4-9e70-6b0a7adcebdd.png)
![image](https://cloud.githubusercontent.com/assets/11298888/6670618/acfd7c72-cbcd-11e4-9790-844473983b48.png)

**Comment by flouthoc** [comment]
@acoreyj Thanks for creating issue and spotting the bug , it'll try to fix this problem ASAP ! Cheers :+1:

**Comment by zhuharev** [comment]
![screenshot from 2015-03-16 22 27 20](https://cloud.githubusercontent.com/assets/10848952/6674571/b2d5fb20-cc2b-11e4-9565-f25e86697f73.png)

Wrong in chromium too.
