### ISSUE TITLE
replace window.onload to event

### ISSUE THREAD

**Issue by zhuharev** [flouthoc/uglipop.js#3]
Your library rewrite window.onload method. It's [wrong](https://ckon.wordpress.com/2008/07/25/stop-using-windowonload-in-javascript/).

Better use `addEventListener` to attach uglipop.js functional

**Comment by flouthoc** [comment]
@zhuharev yeah ! many people told me to do that , i'll do that :smiley:  :+1:  Thanks for creating issue
